### ISSUE TITLE
'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'Regex' to 'Hashable' by implementing 'hash(into:)' instead

### ISSUE THREAD

**Issue by nikhilpandey4** [Flinesoft/HandySwift#41] opened 2020-02-15 05:42 UTC
While building Handyswift with Xcode 11.3 for Swift 5.1, I'm getting this error.

> 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'Regex' to 'Hashable' by implementing 'hash(into:)' instead

**Comment by Jeehut** [comment] 2020-02-21 08:16
@nikhilpandey4 What version of HandySwift are you using? Cause we migrated to `Hash(into:)` 11 months ago in version 3.1.0, see [here](https://github.com/Flinesoft/HandySwift/commit/af625706946b7496dc6999b92627d7013ddace70).

**Comment by nikhilpandey4** [comment] 2020-02-21 12:16
I am  Handy Swift alongside CSV Importer and I am seeing this matter no matter what I version of Handy Swift I use. Also am getting  this error of Switch covers known cases, but 'DispatchTimeInterval' may have additional unknown values, possibly added in future versions.

**Comment by Jeehut** [comment] 2020-02-21 19:24
Ah, I see, yes if you are using it via CSVImporter you get an old version of HandySwift. We can't do anything about it here in HandySwift, I will make a new release of CSVImporter for that. Closing as a duplicate of https://github.com/Flinesoft/CSVImporter/issues/51.

**Closed by Jeehut** 2020-02-21 19:24 UTC
Labels: question
